#!/bin/bash
# chkconfig: 345 99 10
#
#       /etc/rc.d/init.d/<servicename>
#
#       <description of the *service*>
#       <any general comments about this init script>
#
# <tags -- see below for tag definitions.  *Every line* from the top
#  of the file to the end of the tags section must begin with a #
#  character.  After the tags section, there should be a blank line.
#  This keeps normal comments in the rest of the file from being
#  mistaken for tags, should they happen to fit the pattern.>

# Source function library.
. /etc/init.d/functions

WORKING_DIR=/home/remantconnect/webservice-ftp

SCRIPT="$(basename $0)"
DAEMON="/usr/bin/node"
USER="remantconnect"

LOCK_FILE=/var/lock/subsys/${SCRIPT}
SERVER=${WORKING_DIR}/server.js

start() {
  if [ ! -f "$LOCK_FILE" ] ; then
    echo -n $"Starting ${SCRIPT}: "
    runuser -l "$USER" -c "cd ${WORKING_DIR} && ${DAEMON} ${SERVER} &" && echo_success || echo_failure
    echo $?
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
  else
    echo "${SCRIPT} is locked."
    RETVAL=1
  fi
}

stop() {
  echo -n $"Stopping ${SCRIPT}: "
  PIDS=`ps -fe | tr -s " " | grep "${DAEMON} ${SERVER}" | cut -d" " -f 2`

  while read -r PID; do
    echo Killing: $PID
    kill $PID > /dev/null 2>&1 && echo_success || echo_failure
  done <<< ${PIDS}

  if [ -f ${LOCK_FILE} ]; then
    rm -f ${LOCK_FILE}
  fi
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    if [ -f "${LOCK_FILE}" ] ; then
      echo "${SCRIPT} is running"
    else
      echo "${SCRIPT} has stopped"
    fi
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    RETVAL=1
esac
exit $?